<Root>:
    download_label: download_label

    BoxLayout:
        orientation: 'vertical'
        Label:
            text: "YoutubeDownloader"
            font_size: 64
            color: 1, 1, 1
        TextInput:
            font_size: 15
        Label:
            id: download_label
            text: "-"
            font_size: 15
        Button:
            text: "Download"
            font_size: 32
            size: 50, 30
            on_press: root.update()
